name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: graalvm@20.1.0
      - run: git fetch --tags
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: sbt test
