name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: graalvm@20.1.0
      - run: git fetch --tags
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: sbt test
  # native-image:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [macOS-latest, ubuntu-latest]
  #       include:
  #         - os: macOS-latest
  #           artifact: git-mini-x86_64-apple-darwin
  #         - os: ubuntu-latest
  #           artifact: git-mini-x86_64-pc-linux
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: olafurpg/setup-scala@v6
  #     - uses: olafurpg/setup-scala@v6
  #       with:
  #         java-version: graalvm@20.1.0
  #     - run: gu install native-image
  #     - run: sbt native-image
  #     - run: cp gitmini/target/graalvm-native-image/gitmini git-mini
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: ${{ matrix.artifact }}
  #         path: git-mini
